spring:
  application:
    name: test-kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      properties:
        max.request.size: 5097152
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/delta-file-db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 007787898
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: password

server:
  port: 8082
